### PR TITLE
buildmodernize: define g_client_translations=nullptr in a client TU

### PR DESCRIPTION
**Pull request by Desour**
As suggested in <https://github.com/minetest/minetest/pull/15126#discussion_r1793258585>.
This would make `translate_string` have the same behaviour as in master, even in independent srcs.

### CODE REVIEW

**Comment by sfan5** [comment]
but the behaviour is already the same, so is this just to save some `#if`s?

**Comment by Desour** [comment]
>but the behaviour is already the same

In the PR, independent srcs never use `g_client_translations`, no?

**Comment by sfan5** [comment]
ah yeah, that sounds problematic.

**Comment by sfan5** [comment]
squashed into the last commit

**Comment by Desour** [comment]
Could also squash https://github.com/Desour/minetest/commit/54402ab47dab7fa54c0e7f157f400832bf0faea5 in. (less includes by string.h)

**Pull request closed without merging**
